version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: test
    ports:
      - "5432:5432"